### ISSUE TITLE
inconsistency superdense coding chapter

### ISSUE THREAD

**Issue by pptacher** [qiskit-community/qiskit-textbook#1064]
in the last line of step 3 - bob's operations:
-|11>+|10>   gives -|11> after H operation on rightmost qubit.

I think it should be 
+|11>

also in the explanation text, for message "11", operation ZX is applied. in the python code XZ is applied though.

**Comment by paniash** [comment]
@pptacher Hi! Regarding your first question, -|11> is valid since it's a global phase and doesn't physically change the qubit state.

I can partly see why ZX and XZ can create confusion. The intended operation is applying a Z gate first, followed by an X gate for the message "11".  I believe this is what is done in the code as well. Perhaps the table can be changed to "XZ" instead since for example, when writing ZX |q>, we apply X first and then Z. 

Let me know your thoughts! :-)

**Comment by pptacher** [comment]
Hi. I agree -|11> and |11> are physically equivalent. the mathematical result of applying H to the rightmost bit of -|11>+|10> is |11> though,  so why put -|11> ? in my opinion something has to be corrected.

for the second point, if the intended operation is to apply Z first then X, the corresponding mathematical operator is XZ and not ZX (even if in the circuit Z will be on the left and X on its right). but in that case, applying XZ to the rightmost qubit (alice's qubits) of the state 1√2(|00⟩+|11⟩) will give 1√2 ( |01>-|10> ) and not  1√2(  -|01>+|10>) (again 2 physically equivalent states but different mathematically).

Both are just for mathematical correctness and consistency, that won't change anything physically when running the algorithm.

**Comment by flow-g** [comment]
@paniash I just stumbled across the same issue. I absolutely agree with @pptacher about the action of the Hadamard gate..

It doesn't matter that the states are physically equivalent. Mathematically they are not. H(0) |1-> = |11> there is nothing to debate about. Maybe more importantly from a pedagogical point of view this should be corrected.

On the order of the displayed operation for sending the message 11:
1.) if the input is 1√2 ( |00>+|11> ) and the output is 1√2( -|01>+|10>) as in the table then the operation (ZX) has been applied to the right most qubit, which is Alice's according to Qiskit convention. 
2.) The gate representing that operations would be named (ZX)-gate and thus is a sequence of applying gate X first and then gate Z.

In order to get all that in a mathematically and algorithmically consistent form I propose to:
1.) remove the negative sign in front of the |11> state in the "After H-gate" column
2.) remove the discussion about the sign below that table
3.) apply first the x gate and then the z gate in the code.
4.) remove any confusion of the "ZX" operation one could write "Z\cdot X" in the table

Btw just checked that would also agree with https://en.wikipedia.org/wiki/Superdense_coding (attention bit ordering is such that Alice's qubit is the left most one).
