### ISSUE TITLE
Gates Labeling Inconsistency

### ISSUE THREAD

**Issue by almogsr** [qiskit-community/qiskit-textbook#1094]
**Describe the bug**
In Qiskit textbook chapter 3.9 Quantum Counting, there is an issue of inconsistency in how labels for gates are visualized.
qft_dagger.label = "QFT†"
and
cgrit.label = "Grover"
don't generate the same graphics

**To Reproduce**
go through the existing steps in this chapter, and after the Draw() command in 2.4 you can see the problem in the graphics

**Expected behavior**
Either the labels appear on a node, or inside the gate's block

**Version info***
{'qiskit-terra': '0.17.3', 'qiskit-aer': '0.8.2', 'qiskit-ignis': '0.6.0', 'qiskit-ibmq-provider': '0.13.1', 'qiskit-aqua': '0.9.1', 'qiskit': '0.26.0', 'qiskit-nature': '0.1.2', 'qiskit-finance': None, 'qiskit-optimization': '0.1.0', 'qiskit-machine-learning': None}

For website problems please state device / OS / browser.
Win10 and Chrome, latest versions and updates

**Screenshots**
![image](https://user-images.githubusercontent.com/82960897/118442296-188af480-b6f3-11eb-9165-7165501ada79.png)

**Comment by divshacker** [comment]
They will not generate same graphics because there is a difference between two.
The below code is from the notebook itself  that you are talking about.
`# Create controlled-Grover
grit = example_grover_iteration().to_gate()
cgrit = grit.control()
cgrit.label = "Grover"`
If you see this code then the label attribute is applied to `cgrit` and not on `grit`. If you apply it on `cgrit` then it will name the control qubit but if you apply on `grit` then it will apply on the box and not on node.
