### ISSUE TITLE
[4.1.2 Simulating Molecules using VQE] Code example uses Aqua, which is on deprecation path

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-textbook#1331]
### Describe the issue

The code example in https://qiskit.org/textbook/ch-applications/vqe-molecules.html still uses qiskit-aqua, which is being deprecated and it is going to be removed from Qiskit soon (maybe in the next release?):

```python
from qiskit.aqua.algorithms import VQE, NumPyEigensolver
...
from qiskit.aqua.components.optimizers import COBYLA, SPSA, SLSQP
from qiskit.aqua.operators import Z2Symmetries
...
from qiskit.aqua import QuantumInstance
...
```

### Describe what you expect to see

Some part of the text also mention Aqua. The code and the related text needs to be adapted to remove all the references to Aqua. The new code lives in terra. In the text, it would be reasonable to just mention "Qiskit" whenever it says "Aqua" or "Qiskit Aqua".

While the full tutorial needs a rewrite, this issue is about the minimal change required to remove Aqua references and leaves out the pedagogic/style changes that could be considering an enhancement.

**Comment by lockwo** [comment]
For the full tutorial rewrite, would it be good to incorporate the tools from Qiskit nature, or is the goal for these to just use the 'base' Qiskit?

**Comment by 1ucian0** [comment]
I think this issue can be closed if Aqua is removed (I think #1347 does that). A rewrite could be a follow up.

**Comment by divshacker** [comment]
The problem can't be fixed by just changing some of the minor syntax. We need to write code from scratch as there are many changes Qiskit nature which we need to implement in the textbook chapter to make the code compatible to the latest new release.
I have discussed some of the problems with @woodsp-ibm So it will be better if he also explain what problems we are facing.

**Comment by woodsp-ibm** [comment]
Really the main difference is around creating the qubit operator from the molecule as Nature does things a bit different. In Nature you have a driver as before but now there is an ElectronicStructureProblem that builds out the second_q_ops for you which can then be converted to qubit operators using a QubitConvertor. The orbital reduction has been replaced by an ActiveSpaceTransformer and FreezeCoreTransformers to reduce the problem size.

Then HartreeFock and UCCSD take the QubitConvertor that was used to create the operators (instead of specifiying the mapping by string).

Certainly the `get_qubit_op` needs to be completely rewitten. The logic around running VQE needs more like tweaking I think, such as the above HF/UCCSD "tweak" and vqe no longer has a `run` method but is one of a family of minimum eigen solvers (implements an MinimumEigenSolver interface) and has compute_minimum_eigenvalue method that will return the energy result similar to what run did.

You can see this more in this example https://github.com/Qiskit/qiskit-nature#creating-your-first-chemistry-programming-experiment-in-qiskit  I will note that you can get num_particles and num_orbitals directly from the ElectonicStructureProblem after you have called second_q_ops which is simpler that what is shown in the example there where it gets a specific property from the grouped_property of the problem and gets it from there. Since this was common usage there are methods on problem now to directly do this.

Hope this helps.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
