### ISSUE TITLE
Chapter 1: The atoms of computation

### ISSUE THREAD

**Issue by a-vanderbilt** [qiskit-community/qiskit-textbook#1426]
### Describe the bug

The second code exercise in "Your first quantum circuit" does not run, because the "QuantumCircuit" module is not being imported. Adding `from qiskit import QuantumCircuit` to the code editor fixes the error.

### To Reproduce

Run the code in the editor.

### Expected behavior

The code should run and produce output demonstrating the code's functionality.

### Version info

Beta Textbook

### For website problems please state device / OS / browser.

MacBook Air M1 / macOS Monterrey/ Safari 15.4 

### Screenshots

<img width="1179" alt="Screen Shot 2022-05-20 at 11 09 24 PM" src="https://user-images.githubusercontent.com/105957236/169633068-ce6e4f0d-128e-4f94-af28-134709645def.png">
<img width="1179" alt="Screen Shot 2022-05-20 at 11 14 08 PM" src="https://user-images.githubusercontent.com/105957236/169633209-7d68a3b6-2af2-412e-96e7-c3060afe9e41.png">

**Comment by Haemanth-V** [comment]
Hey! So essentially each topic/section in a chapter say "The atoms of computation" is a Jupyter notebook and hence the code present in all the cells is run in the same(single) environment. It is stated clearly at the beginning of the Atoms of computation section that you will have to run the cell which contains all the imports(including that of QuantumCircuit) to be able to run the rest of the code in that section(image attached below). So the problem that you have encountered might probably be because you either forgot to run the import cell or you would have run it long back and the kernel would have died as a result of non-activity which is probably why the imports have not been reflected. Hope that helps and please correct me if I'm wrong :)

![Atoms of computation answering a doubt](https://user-images.githubusercontent.com/59503851/170968300-bc8aa474-a8c7-4af3-8576-fd53b4961173.png)

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
