### ISSUE TITLE
Calibrating qubits using Qiskit Pulse does not work as intended

### ISSUE THREAD

**Issue by Yuval-Toren** [qiskit-community/qiskit-textbook#1432]
When I run the notebook there are two main things that do not work as intended:
1. manila does not support qiskit pulse, only Armonk works with it.
2. instead of getting the expected results I get what seems to be just noise as can be seen here: https://imgur.com/a/o8gUpTT

What can be done to fix this? thanks

**Comment by HuangJunye** [comment]
Having pulse access or not depends on your provider. The open provider only gives pulse access to Armonk. For other devices you can use [pulse gates](https://qiskit.org/documentation/tutorials/circuits_advanced/05_pulse_gates.html) That being said with Armonk getting sunset, we might want to update to notebook to use pulse gates so that all users can still run the same notebook with other systems. @frankharkins What do you think?

**Comment by kUmezawa** [comment]
@HuangJunye @frankharkins Cc @nkanazawa1989 
6-2 has been changed to manila and changed to Pulse Gate.
6-1 has not been changed to Pulse Gate, so I will fix it.
Similarly, modify 6-5 and 6-6 in the same way.

**Comment by kUmezawa** [comment]
@HuangJunye 
Yes, of course, Thank you.

**Comment by HuangJunye** [comment]
I realized I do not have permission to assign. @frankharkins Could you please assign the issue to @kUmezawa ?
