### ISSUE TITLE
[Chapter-3 (Quantum Protocols and Quantum Algorithms)] Sec 3.8  Grover's Algorithm

### ISSUE THREAD

**Issue by MonitSharma** [qiskit-community/qiskit-textbook#1515]
### Describe the issue

In the Example: 2 qubit:  Reflections paragraph, it says 
>>Reflection  U_s. In order to complete the circuit we need to implement the additional reflection  Us=2|s⟩⟨s|−I . Since this is a reflection about |s⟩ , we want to add a negative phase to every state orthogonal to |s⟩ .

It's not a reflection about |s⟩ , it's a reflection about |s'⟩ .

### Describe what you expect to see

The paragraph should be changed to :
>>Reflection  U_s. In order to complete the circuit we need to implement the additional reflection  Us=2|s⟩⟨s|−I . Since this is a reflection about |s'⟩ , we want to add a negative phase to every state orthogonal to |s⟩ .

**Comment by frankharkins** [comment]
I think the original is correct. There are two reflections: the oracle reflects around |s'>, and the diffuser reflects around |s>. Since this step is referring to the diffuser I think it should stay as |s>?

![grover_step3](https://user-images.githubusercontent.com/36071638/202440102-d3400a99-6fb3-4687-8544-1ebc62247749.jpg)

**Comment by MonitSharma** [comment]
Yes. You are correct. I misinterpreted it as the first rotation.   Closing this issue.
Thanks for clearing the doubt.

**Comment by frankharkins** [comment]
No problem, thank you!
