### ISSUE TITLE
Explanation of Global and Relative Phase

### ISSUE THREAD

**Issue by saswati-qiskit** [qiskit-community/qiskit-textbook#387]
## Describe the Issue
There is no or little explanation on global and relative phase

## Expected Solution
It would be good to add more content/explanation on global and relative phase and its significance.

**Comment by frankharkins** [comment]
What would you like to see expanded on, and where do you think this extra explanation should go?

In case you were not already aware, there is a short explanation of global phase [here](https://qiskit.org/textbook/ch-states/representing-qubit-states.html##2-Global-Phase), and a further exploration of the relationship between global and relative phase [here](https://qiskit.org/textbook/ch-gates/phase-kickback.html#2.1-Explaining-the-CNOT-Circuit-Identity-). Maybe these need emphasising.

**Comment by nonhermitian** [comment]
I agree that there needs to be a better explanation of the global phase.  Currently the text just says it disappears during measurement, however the global phase does not matter irrespective of whether a measurement takes place or not.

**Comment by frankharkins** [comment]
@saswati-qiskit are the changes in #407 sufficient? You can see the updated text live at: https://qiskit.org/textbook/ch-states/representing-qubit-states.html##3-Global-Phase

**Comment by nonhermitian** [comment]
I think this is fine for the level at which the textbook is at.  It is a bit incorrect given that the phase does not matter even if no measurement is taken.  The real reason is because only energy differences matter when computing dynamics of systems, but the textbook does not mention unitaries arising from Hamiltonians, so this can not be explained (commutivity would also be handy).

I do take issue with this:
> Since measurements are the only way we can extract any information from a qubit, this implies that these two states are equivalent in all ways that are physically relevant.

This implies that only classical quantities, like those coming from measurements, are physically relevant.  And again, the global phase does not matter even when measurements are not performed, i.e. in Schrodinger's equation.

**Comment by saswati-qiskit** [comment]
Explanation added ...closing the issue.
