### ISSUE TITLE
Prerequistes section should be renamed

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-textbook#409]
## Describe the Issue

The 'prerequisites' section is a resource to help readers who are not experts in python and linear algebra. However, these sections may be off-putting to many readers. If someone thinks that they need to fully understand the linear algebra section before even starting the book, they might not start it at all.

## Expected Solution

* Rename them. 'Appendix' would be better.
* Ensure that the textbook does not rely on them having been read (unless it specifically asks the reader to brush up on a specific topic).

**Comment by quantumjim** [comment]
Or we could have 'prerequisites' with the python, and an appendix with the lin alg. Either way, get that linear algebra info dump out of the doorway!

**Comment by nonhermitian** [comment]
It is good to be clear what is an actual lin alg prerequisite is here. Since this is univ level course, I would assume matrices and vectors. However many places in the text read as if this is not the case. Explicitly stating what the user is assumed to know from the beginning would go a long way in understanding how the text / content should be modified to fit the expected readership level.

**Comment by quantumjim** [comment]
I've found in years of teaching courses on QC and QI that you can't expect a student to know the things they think they know. Since lin alg is so important for us, we will need to teach it as we go along even if we assume they know it already.  

Also, a lot of the ways we use vectors and matrices are motivated by the task at hand. Such as Dirac notation itself, and the way we assign direction to a statevector (in the Bloch sphere), is competely different to the way it is done in classical mechanics. So even for those who know and have used vectors and matrices, there is still much to relearn (the fact that |0> and -|0> are the same thing rather than being opposite things, for example). This is done best by introducing things as we go along.

So I think the level expected is that they known them from classical mechanics, and need to be retaught them for quantum computing.

**Comment by nonhermitian** [comment]
Yes.  But I think we can agree that the notion of a vector and matrix should be background the reader should possess correct?  Basically I think everything listed here:

https://www.khanacademy.org/math/high-school-math

should be considered familiar (but perhaps rusty) material to the reader.  If so then repeatedly saying " if you do not know this then see..." can be avoided many places in the text.

Dirac notation is not really spelled out explicitly in the lin alg section nor the text.  In the lin alg section it is just used for a vector, and in the text it is just noted to be a column vector.

The Bloch sphere is not that difficult as a vector made up of three components in the standard xyz directions.

Things like directions dont matter is actually the physics placing restrictions on the math, as is that we only need normed vectors, so that should be something mentioned.

**Comment by frankharkins** [comment]
Completely agree we need to be more clear about what prerequistes are required, and that the purpose of the reminders / relearnings are not to teach the material for the first time. I do think they also serve the purpose of acknowledging when key mathematical ideas occur so that the reader has a cue to refresh themselves on them if needed.

After some discussion with Jim, we thought it might be good to have up to & inc. 2.3 accessible to people with rusty knowledge of the Khan academy course you mentioned. Then we can re-insert [fun with matrices](https://github.com/Qiskit/qiskit-textbook/blob/master/content/ch-gates/fun-matrices.ipynb), as a recap of the maths they'll need to continue with the textbook.
