### ISSUE TITLE
Wrong function argument used in Composite Gates section of Advanced Circuit Tutorials

### ISSUE THREAD

**Issue by salihyanikgonul** [qiskit-community/qiskit-textbook#633]
**Wrong function argument in Composite-Gates section code snippet**:

In [Composite Gates section of the Qiskit tutorial](https://qiskit.org/documentation/tutorials/circuits_advanced/1_advanced_circuits.html#Composite-Gates), the code snippet 
shown below mistakenly uses**qr** register declared on the [Opaque Gates section](https://qiskit.org/documentation/tutorials/circuits_advanced/1_advanced_circuits.html#Opaque-gates) as function argument. 
```
# Convert to a gate and stick it into an arbitrary place in the bigger circuit
sub_inst = sub_circ.to_instruction()

q = QuantumRegister(3, 'q')
circ = QuantumCircuit(q)
circ.h(qr[0])
circ.cx(qr[0], qr[1])
circ.cx(qr[1], qr[2])
circ.append(sub_inst, [q[1], q[2]])

circ.draw()
```
For consistency, it should use **q** register defined for this newly created **circ**, not **qr** register which is defined for another **circ** in the previous [Opaque gates](https://qiskit.org/documentation/tutorials/circuits_advanced/1_advanced_circuits.html#Opaque-gates) section. Therefore, the code snippet should be modified as follows:
```
# Convert to a gate and stick it into an arbitrary place in the bigger circuit
sub_inst = sub_circ.to_instruction()

q = QuantumRegister(3, 'q')
circ = QuantumCircuit(q)
circ.h(q[0])
circ.cx(q[0], q[1])
circ.cx(q[1], q[2])
circ.append(sub_inst, [q[1], q[2]])

circ.draw()
```

**Comment by sinkomr** [comment]
Looks like somebody fixed this, the quantum registers are now "qr" throughout, with no switching from 'qr' to 'q' but then using 'qr' in the circuit like you show above.
I think this is a satisfactory conclusion because it is consistent throughout and since the 'qr' quantum register is newly declared in the composite gates section, there will be no mixture with the 'qr' quantum register that was declared in the opaque gates section

I did not make this change, I just noticed it while looking into this issue you posted

# Convert to a gate and stick it into an arbitrary place in the bigger circuit
sub_inst = sub_circ.to_instruction()

qr = QuantumRegister(3, 'q')
circ = QuantumCircuit(qr)
circ.h(qr[0])
circ.cx(qr[0], qr[1])
circ.cx(qr[1], qr[2])
circ.append(sub_inst, [qr[1], qr[2]])

circ.draw()### ###

**Comment by vabarbosa** [comment]
this appears to have been resolved

<img width="856" alt="image" src="https://user-images.githubusercontent.com/13156555/100759639-d8db8500-33be-11eb-8a1f-c28ba290dff2.png">
