### ISSUE TITLE
A chapter on cold atom physics

### ISSUE THREAD

**Issue by Aniruddha120** [qiskit-community/qiskit-textbook#645]
**What should the reader gain from this new content?**
Explain the clear end goals of the chapter (After reading this chapter the student will understand [...]).
Previously a lot of research has been done on cold atom physics by the help of quantum computing(qiskit was also involved!!) and an example can meet the students with real-time scenarios
**Where do you expect this new content to fit in with the current content?**
Under section 4
Where will this place in the current table of contents? And what other content will need to change to accomodate it (prerequisite material etc.)?
Discussion needed
*Are you proposing to write this new content?* (y/n)
No, it needs a deeper understanding. But, I think the book should provide an idea about the topic for the newcomers. 

The research paper:[ link](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiPl6bes4LrAhXYzzgGHQbFBkwQFjAHegQIChAB&url=https%3A%2F%2Farxiv.org%2Fpdf%2F1712.07326&usg=AOvVaw0uRaPL7SSMdjDjyMS2A-9t)

**Comment by frankharkins** [comment]
@Aniruddha120 I am closing this issue because you have not explained the clear end goals of the chapter, and I have no idea of what the chapter should cover. The link you posted looked interesting, maybe you could open an issue suggesting a chapter in 4.2 implementing that paper, then the end goal of the chapter would be "Reader will understand how to simulate a particle in a potential barrier using a quantum computer". This end goal is much more achievable.
