### ISSUE TITLE
Add N-qubits case (matrix way) to construct phase oracle

### ISSUE THREAD

**Issue by kitaev-chen** [qiskit-community/qiskit-textbook#665]
**Is your feature request related to a problem? Please describe.**
The [grover algorithm](https://qiskit.org/textbook/ch-algorithms/grover.html) addressed in the qiskit textbook is very good and clear, but it missed the N-qubits case.

**Describe the solution you'd like**
first, it needs a summary/analysis for the common pattern of the circuit construction of the 2, 3, 4... qubits cases. On the other side, it should be mentioned the easier (matrix) way when coding implements.

**Describe alternatives you've considered**
it will make the beginner confusion and waste of lots of time without mention that in real implements people don't construct N-qubits phase oracle like this, just a NumPy matrix is enough.

**Additional context**
N/A

**Comment by diemilio** [comment]
I actually have been thinking about this for some time now, and have some suggestions.

Explaining that a diagonal unitary with marked elements is definitely a simple and general way to express the oracle; however, on its own, it does not provide the reader a good understanding of how the circuit itself could be implemented. It could be argued that we can have a transpiler take care of transforming the unitary into basis gates, but to me, it would seem that this approach takes away the opportunity of helping the reader build an intuition on how oracles are turned into actual gates.

A solution could be to explain the diagonal unitary for the oracle can be constructed by the use of uniformly controlled Rz ([ucrz](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.ucrz.html)) gates, just as described in theorem 7 of this [reference](https://arxiv.org/pdf/quant-ph/0406176.pdf). This is actually the way the [Diagonal circuit](https://qiskit.org/documentation/stubs/qiskit.circuit.library.Diagonal.html) for Qiskit's circuit library is composed.

I think this could be a good enhancement to the section, but it might require some careful writing. Another change could be to generalize the oracle used in the sample code so it can be placed within `qiskit_textbook.tools`, similar to what is done for Simon's algorithm.

**Comment by frankharkins** [comment]
Another alternative that was suggested to me recently to construct simple circuits that identify features of the states. For example, instead of saying 
> here's a circuit that marks the states 110 and 111
we say
> let's mark states that are greater than 6 (first two qubits need to be `1`)
Maybe I misunderstand, but I don't see how a diagonal matrix is any closer to 'real' implementations.

**Comment by frankharkins** [comment]
I am assigning myself this and will take the approach of marking properties of different states as per my comment above. I will include an explanation as to how a numpy matrix could also be used to construct an oracle as I believe this will help readers experiment. Please let me know if you have any thoughts on this.

**Comment by Hirmay** [comment]
I have a good idea for numpy matrix part, if you want I can give a shot at the numpy matrix part?

**Comment by diemilio** [comment]
@frankharkins, sounds good. Sorry for the late reply; I was out last week with no computer access. I have a document on Grover's Oracle that I've been working on that might be of help. This was not necessarily intended for the textbook, but I will share it tonight or tomorrow morning to see if you find anything in there that might be of use.

**Comment by frankharkins** [comment]
@Hirmay what did you have in mind?

**Comment by Hirmay** [comment]
I had something like this in mind for numpy matrix let me know if I should make some changes or it differs from you envision it.
`def phase_oracle(n, indices_to_mark, name = 'Oracle'):
    
    Grover_circuit = QuantumCircuit(n, name=name)

    oracle_matrix = np.identity(2**n)
    for i in indices_to_mark:
        oracle_matrix[indices_to_mark, indices_to_mark] = -1 

    Grover_circuit.unitary(Operator(oracle_matrix), range(n))
    
    return Grover_circuit
def diffuser(n):
    
    Grover_circuit = QuantumCircuit(n, name='Diffuser')
    Grover_circuit.h(range(n))
    Grover_circuit.append(phase_oracle(n, [0]), range(n))
    Grover_circuit.h(range(n))

    return Grover_circuit

def Grover(n, indices_of_marked_elements):
    
    Grover_circuit = QuantumCircuit(n, n)

    rounds = int(np.floor(np.pi/4*np.sqrt(2**n/len(indices_of_marked_elements))))
    print(f"{n} qubits, basis states {indices_of_marked_elements} marked, {rounds} rounds")

    Grover_circuit.h(range(n))
    
    for _ in range(rounds):
        Grover_circuit.append(phase_oracle(n, indices_of_marked_elements), range(n))
        Grover_circuit.append(diffuser(n), range(n))
        
    Grover_circuit.measure(range(n), range(n))
  
    return Grover_circuit`

**Comment by frankharkins** [comment]
@Hirmay, @diemilio: I maybe misunderstand your suggestion, but I'm still not sure how constructing the oracle from a matrix is more instructive than what we currently have. It still requires knowledge of the 'solution' a priori, and is impractical for large numbers of qubits.

My plan was to rewrite a portion of the article according to my comment above:

> Another alternative that was suggested to me recently to construct simple circuits that identify features of the states. For example, instead of saying:
> > here's a circuit that marks the states `110` and `111`
> we say:
> > let's mark states that are greater than 6 (first two qubits need to be `1`)

I think it's worth explaining that a Grover oracle is a diagonal matrix of the form you mention, and briefly showing we can convert between the matrix form and the quantum circuit, but I don't see the value in using a matrix as the main representation of the oracle.

As I say, maybe I misunderstand your suggestions so please correct me if that is the case.

**Comment by Hirmay** [comment]
Yeah I agree that we should use matrix as the main representation of oracle but it's a good to show the conversion between matrix form and quantum circuit like you said. I would just like to add that if you add

> let's mark states that are greater than 6 (first two qubits need to be `1`)

Then you might also need to put some context what do you mean by states greater than 6 if we haven't used that convention before.

**Comment by diemilio** [comment]
Hi @frankharkins, here are my thoughts on this matter:

- First off, I think it is important to note that when using a phase oracle of the form 𝑈𝑓 |𝑥⟩ = (−1)^𝑓(𝑥) |𝑥⟩, the unitary associated with 𝑈𝑓 is always a diagonal matrix where the position associated with the unmarked elements is equal to 1, and the position associated with marked elements are equal to -1. This is always the case independently of the circuit used to implement 𝑈𝑓. So, even if we were to write down the operator for the 2-qubit and 3-qubit examples currently in the textbook, they will have matrices of that form.
- I agree that there is nothing wrong with the way this is currently explained in the textbook. As I mentioned in my first comment, I actually like the way is presented because it helps the reader understand how oracles for different cases can be implemented at the gate level.
- Where the textbook might be falling short is in explaining how could be potentially generalize the implementation of the oracle for the case where we have _n_ qubits instead of just 2 or 3. If we, for example, look at the [reference](https://arxiv.org/pdf/1703.10535.pdf) used in the textbook for the 3-qubit case, we can see that tables I and II provide all the circuits for all 28 possible Oracles; however, there is no description of how these circuits can be implemented in a systematic way. Furthermore, if instead of wanting an Oracle for 3 qubits, we needed an oracle for 4, 5, or _n_ qubits, there really isn't an explanation on how to achieve this.
- I believe it is for this reason that @kitaev-chen opened this issue. From his description, it seems to me that what he is proposing is to implement something along the lines of what @Hirmay has suggested. The advantage of constructing the oracle this way is that it can reside on a separate callable function that can take any number of n-qubit marked elements, and generate the oracle. This will be very similar to the way the oracles for the Deutsch-Jozsa, Bernstein-Vazirani and Simon's algorithm are currently implemented in the textbook. The user can provide any number of qubits n and the secret string, and the function generates the oracle.
- Now, the disadvantage is that, unlike the oracles for DJ, BV and Simon's, the method they are suggesting simply takes the diagonal matrix and appends it to a circuit using the `unitary` class method of the `QuantumCircuit`. This is what I was trying to point out in my first message. I think that doing this takes away any intuition of how the circuit for the oracle can be constructed at the gate level, as is currently done in the textbook. After all, we want to not only have a function that generates our oracle, but we want to explain how it is done.
- The question then is: Is there a way to construct the circuit of a n-qubit phase-oracle using gates (rather than the `unitary` method) in a way that can be "automated" just as it is for the other textbook algorithms? As I also mentioned in my first message, the answer is yes, but describing how to do this in Qiskit might be a bit tricky. Here is a [notebook](https://nbviewer.jupyter.org/github/diemilio/Grovers_Algorithm_Animation/blob/master/Grovers_n-qubit_Oracle.ipynb) where I have a short description of how this can be done.
- The first implementation described in the notebook explains the same method suggested by @kitaev-chen and @Hirmay. The second implementation is a way to generate an n-qubit phase-oracle by the use of multi-control cz gates. This is a personal document I have been working on, so it might be missing some details of how the ucrz gates are used as cz gates, but that can be added.

I guess the questions that would need to be answered are:
1. Is it important is to describe the implementation of an n-qubit phase-oracle in the textbook?
2. If explaining the n-qubit implementation of the oracle _is_ important, then is it OK just to explain the `unitary` method?

It is possible that the answer to both of these question is **no**, in which case no changes will be needed. 

Hope this helps clarify things a bit.

**Comment by frankharkins** [comment]
> 1. Is it important is to describe the implementation of an n-qubit phase-oracle in the textbook?

At the moment, we provide oracles that select predetermined states (e.g. "here is an oracle that selects the state `011`"). IMO it is not really useful to explain how to create n-qubit oracles like this as (unlike DJ / BV / Simon) Grover promises to solve a 'useful' problem. Hence the suggestion to create oracles that solve problems where we do not know the solution a priori (even if you could solve through simple inspection). E.g. "here is an oracle that selects odd numbers between 2 and 4 (`011`)".

> 2. If explaining the n-qubit implementation of the oracle is important, then is it OK just to explain the unitary method?

I think it's worth explaining the form of the oracle will be a diagonal matrix as you mention as this may make the behaviour clearer to some readers. If we are to do this, it is only an extra line to show you can easily turn a matrix into an oracle.

**Comment by frankharkins** [comment]
@kitaev-chen @diemilio @Hirmay after thinking about your comments for a while, I think I see a different angle that I did not before: The chapter should focus on teaching Grover's algorithm and not oracle construction.

While I don't believe we should fully separate the two, I see the value in using "black box" oracles so we can tackle one concept at a time. With that in mind, here is a first draft of the "Oracles" section:

<img width="596" alt="Screenshot 2020-08-24 at 16 04 52" src="https://user-images.githubusercontent.com/36071638/91062474-a6cec000-e624-11ea-9a1c-0815d1584bd2.png">

(I am uploading an image to preserve formatting, but please let me know if this is not accessible to you).

**Comment by Hirmay** [comment]
I think you have done a very good job for this section but I have one question do we tell the students in previous topics, that why applying CNOT on the last qubit in state |0> doesn't violate No-Cloning theorem? If not you can add a section somewhere explaining this which would be very useful for the students.

**Comment by frankharkins** [comment]
@Hirmay can you elaborate on that please? I'm not sure I've come across that misconception before.

**Comment by Hirmay** [comment]
When I was doing a course online many people were confused why in circuits does applying CNOT here to |0> we get |f(x)>. I thought that here also many students could have that doubt of why doesn't it violate No-Cloning theorem.[
![misconcept](https://user-images.githubusercontent.com/56473003/91067372-713fcc00-e650-11ea-8047-eb3c794c41fa.PNG)
](url)

**Comment by frankharkins** [comment]
Ah, would it be clearer if instead of |𝑓(𝑥)⟩ it was 0⊕|𝑓(𝑥)⟩?

**Comment by frankharkins** [comment]
Also, @Hirmay may I please have your permission to use the code in [this comment](https://github.com/qiskit-community/qiskit-textbook/issues/665#issuecomment-674802109)? I will add you as a co-author in the commit.

**Comment by Hirmay** [comment]
> Also, @Hirmay may I please have your permission to use the code in [this comment](https://github.com/qiskit-community/qiskit-textbook/issues/665#issuecomment-674802109)? I will add you as a co-author in the commit.

Yeah sure go ahead, I don't have any issues.



> Ah, would it be clearer if instead of |𝑓(𝑥)⟩ it was 0⊕|𝑓(𝑥)⟩?

It could work but I think maybe we could explain it in more detail where No-Cloning theorem was mentioned as a note or maybe even as a question like why in this case does No-Cloning theorem doesn't get violate.

**Comment by frankharkins** [comment]
@Hirmay do you want to write that explanation?

**Comment by Hirmay** [comment]
Yeah sure I'll write one and post it here.

**Comment by Hirmay** [comment]
I have come up with something like this, please let me know if you want like any changes in this.

![Answer](https://user-images.githubusercontent.com/56473003/91126184-0b3f5d00-e6c1-11ea-9031-0e66b083855e.PNG)

**Comment by frankharkins** [comment]
I'm not sure about this:

> ...this procedure does not violate the no-cloning theorem because it's certain |𝑓(𝑥)⟩ will be one of two known orthogonal states. If |𝑓(𝑥)⟩ was an arbitrary superposition of 0 and 1, this would not be possible.

This makes it sound (to me) like the CNOT does not work correctly on superpositions of states.

I believe in this paragraph you are essentially explaining "It is possible to clone classical states, but not quantum superpositions"? If so, would this be more appropriate to discuss where the no-cloning theorem is first introduced? My reasoning is that if the student has this confusion, it is because of a problem with the current explanation of no-cloning. Additionally, if the reader has this misconception, they will likely have worked through problems such as the Deutsch-Jozsa problem which use similar oracles.

**Comment by diemilio** [comment]
> The chapter should focus on teaching Grover's algorithm and not oracle construction.

> While I don't believe we should fully separate the two, I see the value in using "black box" oracles so we can tackle one concept at a time. With that in mind, here is a first draft of the "Oracles" section

@frankharkins, I think this makes a lot of sense, especially if the idea is to have a section on oracles, which could be referenced under each of the algo’s sections. This will help those who want to learn more about their implementation without adding that distraction when trying to learn about the algorithm itself.

**Comment by Hirmay** [comment]
> I'm not sure about this:
> 
> > ...this procedure does not violate the no-cloning theorem because it's certain |𝑓(𝑥)⟩ will be one of two known orthogonal states. If |𝑓(𝑥)⟩ was an arbitrary superposition of 0 and 1, this would not be possible.
> 
> This makes it sound (to me) like the CNOT does not work correctly on superpositions of states.
> 
> I believe in this paragraph you are essentially explaining "It is possible to clone classical states, but not quantum superpositions"? If so, would this be more appropriate to discuss where the no-cloning theorem is first introduced? My reasoning is that if the student has this confusion, it is because of a problem with the current explanation of no-cloning. Additionally, if the reader has this misconception, they are likely to encounter problems such as the Deutsch-Jozsa problem which use similar oracles before they reach Grover..

Yeah I was thinking to discuss where no-cloning theorem is first introduced(Which was in probably quantum teleportation).

**Comment by frankharkins** [comment]
@Hirmay what email should I use to add you as a co-author? This can be your github no-reply email if you want to keep your personal email private.

**Comment by Hirmay** [comment]
No you can add my real id which hirmaysandesara@gmail.com

**Comment by frankharkins** [comment]
You can see the chapter with the changes I have been working on [here](https://github.com/qiskit-community/qiskit-textbook/blob/oracle-changes/content/ch-algorithms/grover.ipynb). If you have the time, I would appreciate feedback. Main changes are:
- Remove emphasis on creating specific oracles (e.g. oracle for |00>, |01>, |10>).
- Add description of oracle as diagonal matrix.
- Add `grover_problem_oracle` function to the `qiskit_textbook` package.
- Generalise initialising & diffuser code.
- Update questions to be more instructive (working towards #655).
- Give example of how we can solve a classical problem using Grover's algorithm.

To do:
- (maybe) show method of creating oracle through qiskit's [diagonal circuit](https://qiskit.org/documentation/stubs/qiskit.circuit.library.Diagonal.html).

**Comment by diemilio** [comment]
Hi @frankharkins,

If you decide to include the method of creating the oracle using Qiskit's diagonal circuit, and don't want to spend the time coding it, I already have done this. It is fairly simple, but you can find it here:
https://nbviewer.jupyter.org/github/diemilio/Grovers_Algorithm_Animation/blob/master/Grovers_Algorithm_Basic.ipynb

I changed my code for the number of oracle/diffuser "rounds" to match @Hirmay's code for consistency.

**Comment by frankharkins** [comment]
@kitaev-chen do you believe the changes made are sufficient to close this issue? You can check out the updated version on the live site: https://qiskit.org/textbook/ch-algorithms/grover.html

**Comment by frankharkins** [comment]
I am closing this but feel free to re-open if you feel the issue has not been sufficiently addressed.
