### ISSUE TITLE
6.4 where does sigma_x come from?

### ISSUE THREAD

**Issue by HTransistor** [qiskit-community/qiskit-textbook#799]
**Describe the issue**
1. Where does sigma_x in the last equation come from? Before we were dealing just with sigma_z.

2. In equation 2 it is not clear why from the commutator of sigma_+- terms the result is sigma_z. What is the [sigma_+, sigma_-]. It would be good to mention this in the textbook.

![6_4_sigma_x](https://user-images.githubusercontent.com/43704364/96859017-48c22b80-1461-11eb-881c-4b1affd9e3ab.png)

**Comment by divshacker** [comment]
Hey @HTransistor I would like to work on this issue. I agree with your first point. The sigma_x should change to sigma_z.
For point 2 can you please describe it more what exactly you are expecting to add to provide more context to [sigma_+, sigma_-]?

**Comment by HTransistor** [comment]
It looks like [sigma_+, sigma_-] = -sigma_z
[sigma_-, sigma_+] = sigma_z. I think it is a good idea to mention this, to get a more fluent read on the calculations.
You could even get into more detail sigma_+- = sigma_x +- i * sigma_y and use the commutator relations.

**Comment by nbronn** [comment]
Hi there! Those commutation relations are correct, but the $\sigma^x$ arises from the $\sigma^+ + \sigma^-$ that arises in in the last term of the first equation when the qubit drive is set to be real, $\Omega^* = \Omega$ (in general, a complex drive just changes the angle of the axis in the x-y plane of the Bloch sphere which the qubit is driven around).

**Comment by divshacker** [comment]
Well If we choose previous version as correct one then still that doesn't answer from where sigma_x came from. I think we need to define sigma_x and sigma_z to bring more clarity ?
I am happy to have suggestions 🙂

**Comment by nbronn** [comment]
For clarity, perhaps the reader can recall that $\omega^{\pm} = \frac{1}{2} (\sigma^x \mp i\sigma^y)$ is the definition of the spin raising/lowering operator. If one chooses $\Omega$ to be real, then $\Omega^* = \Omega$ in the first equation above, then we are left with only the $\sigma^x$ term, because $\sigma^x = \sigma^+ + \sigma^-$ from the definition. If instead, we chose $\Omega$ to be purely imaginary, then $\Omega^* = -\Omega$, and we are left with only $\sigma^y = \sigma^+ - \sigma^-$. This is because the 90 degree rotation in the complex plane (real -> imaginary) corresponds to a 90 degree rotation of axis in the $xy$-plane ($\hat{x}$- -> $\hat{y}$-axis).
